# Generated by Django 3.0.5 on 2020-05-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atgexp', '0004_auto_20200515_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image_url',
            new_name='image',
        ),
    ]
